### ISSUE TITLE
Renamer - Add file renaming with performer names

### ISSUE THREAD

**Issue by pornman1500** [Whisparr/Whisparr#56] opened 2023-03-08 22:13 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Current renamer doesn't allow for a performer name field

### Describe the solution you'd like

Allow to have performer names to be added to file names

### Describe alternatives you've considered

Could also allow for having site and subsite renaming or other fields in the renamer

**Comment by thezak48** [comment] 2023-03-12 05:30
Duplicate of #15

**Closed as not planned by thezak48** 2023-03-12 05:30 UTC
Labels: Status: Needs Triage, Type: Feature Request
