### ISSUE TITLE
Whisparr v2 repo - Prowlarr not working

### ISSUE THREAD

**Issue by MrMxyzptlk** [Whisparr/Whisparr#54] opened 2023-02-20 17:01 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Prowlarr won't sync with Whisparr v2; it will with the v1 repo.
It probably has something to do with the forced authentication.
I have both certs and login set to disable for local addresses, as I have no external exposure.

Because of the Prowlarr issue I can't add most of my torrent indexers.

### Expected Behavior

Sync with Prowlarr.

### Steps To Reproduce

Add my Whisparr v2 instance to Prowlarr apps, and sync indexers.

Basic was not authenticated. Failure message: Authorization header missing.

### Environment

```markdown
- OS: Windows
- Whisparr: latest v2
- Docker Install: N/A
- Using Reverse Proxy: N/A
- Browser: latest Chrome on Mac Ventura
```

### What branch are you running?

Other (This issue will be closed)

### Trace Logs?

N/A

**Comment by sauriodino** [comment] 2023-06-06 11:16
I have the same problem but in docker

**Comment by thezak48** [comment] 2023-06-06 12:03
Can we get trace logs of an attempted sync

**Comment by ranrinc** [comment] 2023-07-01 07:20
anyone solve the problem? Authentications issue and did not solve.

**Comment by thezak48** [comment] 2023-07-02 10:41
Without logs of the issue we have no idea what the issue is

> Can we get trace logs of an attempted sync

**Comment by Qstick** [comment] 2023-07-04 23:09
Closing until we get logs to work with

**Closed as not planned by Qstick** 2023-07-04 23:09 UTC
