### ISSUE TITLE
Evil Angel Scenes Not pulling for year 2020 (and possibly other years)

### ISSUE THREAD

**Issue by cmcooper1980** [Whisparr/Whisparr#61] opened 2023-03-29 20:52 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I am attempting to manually import several scenes from Evil Angel for year 2020 (and possibly other years) and only 2 scenes populate

(attached screenshot)
![image](https://user-images.githubusercontent.com/31871143/228659010-0fa65d78-c8b9-4dba-813b-6928adac13de.png)

### Expected Behavior

Expected that when year 2020 from Evil Angel is selected all matching scenes from that year, if they exist on TPDB, to populate list for selection

### Steps To Reproduce

-Have a video file from Evil Angel from 2020
-goto Wanted in Whisparr and click Manual Import
-select file location to import from
-choose Evil Angel as the Site
-choose year 2020
-see only 2 scenes instead of all scenes featured in TPDB

### Environment

```markdown
- OS: Ubuntu Server 20.04.2 LTS
- Whisparr: 2.0.0.139
- Docker Install: 23.0.1
- Using Reverse Proxy: Nginx Proxy Manager
- Browser: Google Chrome
```

### What branch are you running?

Main

### Trace Logs?

2023-03-29 15:37:38.0|Trace|EventAggregator|ConfigFileSavedEvent <~ ReconfigureLogging
2023-03-29 15:37:38.0|Trace|EventAggregator|ConfigSavedEvent -> UiAuthorizationHandler
2023-03-29 15:37:38.0|Trace|EventAggregator|ConfigSavedEvent <- UiAuthorizationHandler
2023-03-29 15:37:38.0|Trace|EventAggregator|ConfigSavedEvent ~> LocalizationService
2023-03-29 15:37:38.0|Trace|EventAggregator|ConfigSavedEvent ~> TaskManager
2023-03-29 15:37:38.0|Trace|ConfigService|Using default config value for 'enablecompleteddownloadhandling' defaultValue:'True'
2023-03-29 15:37:38.0|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2023-03-29 15:37:38.0|Trace|EventAggregator|Publishing HealthCheckCompleteEvent
2023-03-29 15:37:38.0|Trace|EventAggregator|HealthCheckCompleteEvent -> HealthController
2023-03-29 15:37:38.0|Trace|EventAggregator|ConfigSavedEvent <~ LocalizationService
2023-03-29 15:37:38.0|Trace|EventAggregator|HealthCheckCompleteEvent <- HealthController
2023-03-29 15:37:38.0|Trace|EventAggregator|HealthCheckCompleteEvent ~> NotificationService
2023-03-29 15:37:38.0|Trace|EventAggregator|HealthCheckCompleteEvent <~ NotificationService
2023-03-29 15:37:38.0|Trace|ConfigService|Using default config value for 'rsssyncinterval' defaultValue:'15'
2023-03-29 15:37:38.0|Trace|ConfigService|Using default config value for 'backupinterval' defaultValue:'7'
2023-03-29 15:37:38.0|Trace|EventAggregator|ConfigSavedEvent <~ TaskManager
2023-03-29 15:37:38.0|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2023-03-29 15:37:38.0|Trace|ConfigService|Using default config value for 'proxytype' defaultValue:'Http'
2023-03-29 15:37:38.0|Trace|ConfigService|Using default config value for 'proxyhostname' defaultValue:''
2023-03-29 15:37:38.0|Trace|ConfigService|Using default config value for 'proxyport' defaultValue:'8080'
2023-03-29 15:37:38.0|Trace|ConfigService|Using default config value for 'proxyusername' defaultValue:''
2023-03-29 15:37:38.0|Trace|ConfigService|Using default config value for 'proxypassword' defaultValue:''
2023-03-29 15:37:38.0|Trace|ConfigService|Using default config value for 'proxybypassfilter' defaultValue:''
2023-03-29 15:37:38.0|Trace|ConfigService|Using default config value for 'proxybypasslocaladdresses' defaultValue:'True'
2023-03-29 15:37:38.0|Trace|ConfigService|Using default config value for 'certificatevalidation' defaultValue:'Enabled'
2023-03-29 15:37:38.0|Trace|ConfigService|Using default config value for 'backupfolder' defaultValue:'Backups'
2023-03-29 15:37:38.0|Trace|ConfigService|Using default config value for 'backupinterval' defaultValue:'7'
2023-03-29 15:37:38.0|Trace|ConfigService|Using default config value for 'backupretention' defaultValue:'28'
2023-03-29 15:37:38.0|Trace|ConfigService|Using default config value for 'applicationurl' defaultValue:''
2023-03-29 15:37:38.0|Trace|Http|Res: 13747 [PUT] /api/v3/config/host: 202.Accepted (222 ms)
2023-03-29 15:37:38.0|Debug|Api|[PUT] /api/v3/config/host: 202.Accepted (222 ms)
2023-03-29 15:37:38.1|Trace|Http|Req: 13748 [GET] /api/v3/health (from 172.*.*.89 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36)
2023-03-29 15:37:38.1|Trace|Http|Res: 13748 [GET] /api/v3/health: 200.OK (4 ms)
2023-03-29 15:37:38.1|Debug|Api|[GET] /api/v3/health: 200.OK (4 ms)
2023-03-29 15:37:38.2|Trace|Http|Req: 13749 [GET] /api/v3/health (from 172.*.*.89 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36)
2023-03-29 15:37:38.2|Trace|Http|Res: 13749 [GET] /api/v3/health: 200.OK (2 ms)
2023-03-29 15:37:38.2|Debug|Api|[GET] /api/v3/health: 200.OK (2 ms)
2023-03-29 15:37:43.1|Trace|Http|Req: 13750 [GET] /api/v3/wanted/missing?page=1&pageSize=20&sortDirection=descending&sortKey=episodes.airDateUtc&monitored=true (from 172.*.*.89 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36)
2023-03-29 15:37:43.6|Trace|Http|Res: 13750 [GET] /api/v3/wanted/missing?page=1&pageSize=20&sortDirection=descending&sortKey=episodes.airDateUtc&monitored=true: 200.OK (542 ms)
2023-03-29 15:37:43.6|Debug|Api|[GET] /api/v3/wanted/missing?page=1&pageSize=20&sortDirection=descending&sortKey=episodes.airDateUtc&monitored=true: 200.OK (542 ms)
2023-03-29 15:37:43.8|Trace|Http|Req: 13751 [GET] /api/v3/queue/details?episodeIds=167386&episodeIds=167410&episodeIds=167409&episodeIds=167408&episodeIds=50069&episodeIds=167407&episodeIds=167406&episodeIds=167403&episodeIds=167405&episodeIds=173301&episodeIds=173302&episodeIds=173303&episodeIds=173304&episodeIds=173305&episodeIds=167400&episodeIds=167399&episodeIds=50067&episodeIds=50066&episodeIds=50065&episodeIds=50051 (from 172.*.*.88 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36)
2023-03-29 15:37:43.8|Trace|Http|Res: 13751 [GET] /api/v3/queue/details?episodeIds=167386&episodeIds=167410&episodeIds=167409&episodeIds=167408&episodeIds=50069&episodeIds=167407&episodeIds=167406&episodeIds=167403&episodeIds=167405&episodeIds=173301&episodeIds=173302&episodeIds=173303&episodeIds=173304&episodeIds=173305&episodeIds=167400&episodeIds=167399&episodeIds=50067&episodeIds=50066&episodeIds=50065&episodeIds=50051: 200.OK (2 ms)
2023-03-29 15:37:43.8|Debug|Api|[GET] /api/v3/queue/details?episodeIds=167386&episodeIds=167410&episodeIds=167409&episodeIds=167408&episodeIds=50069&episodeIds=167407&episodeIds=167406&episodeIds=167403&episodeIds=167405&episodeIds=173301&episodeIds=173302&episodeIds=173303&episodeIds=173304&episodeIds=173305&episodeIds=167400&episodeIds=167399&episodeIds=50067&episodeIds=50066&episodeIds=50065&episodeIds=50051: 200.OK (2 ms)
2023-03-29 15:37:47.4|Trace|Http|Req: 13752 [GET] /api/v3/manualimport?folder=%2Fmnt%2Fxxx2%2F_unsorted%2F&filterExistingFiles=true (from 172.*.*.88 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36)
2023-03-29 15:37:47.5|Debug|Parser|Parsing string '_unsorted'
2023-03-29 15:37:47.5|Debug|Parser|Unable to parse _unsorted
2023-03-29 15:37:47.5|Debug|DiskScanService|Scanning '/mnt/xxx2/_unsorted/' for video files
2023-03-29 15:37:47.5|Trace|DiskScanService|601 files were found in /mnt/xxx2/_unsorted/
2023-03-29 15:37:47.5|Debug|DiskScanService|600 video files were found in /mnt/xxx2/_unsorted/
2023-03-29 15:37:47.5|Warn|ManualImportService|Unable to determine series from folder name and found more than 100 files. Skipping parsing
2023-03-29 15:37:47.6|Trace|Http|Res: 13752 [GET] /api/v3/manualimport?folder=%2Fmnt%2Fxxx2%2F_unsorted%2F&filterExistingFiles=true: 200.OK (122 ms)
2023-03-29 15:37:47.6|Debug|Api|[GET] /api/v3/manualimport?folder=%2Fmnt%2Fxxx2%2F_unsorted%2F&filterExistingFiles=true: 200.OK (122 ms)
2023-03-29 15:37:55.2|Trace|Scheduler|Pending Tasks: 0
2023-03-29 15:38:02.2|Trace|Http|Req: 13753 [POST] /api/v3/manualimport (from 172.*.*.89 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36)
2023-03-29 15:38:02.2|Debug|ManualImportService|Language couldn't be parsed from release, falling back to series original language: English
2023-03-29 15:38:02.2|Debug|ImportDecisionMaker|Analyzing 1/1 files.
2023-03-29 15:38:02.2|Debug|VideoFileInfoReader|Getting media info from /mnt/xxx2/_unsorted/evilangel.20.09.23.paige.owens.oil-soaked.anal.gaping.mp4
2023-03-29 15:38:02.3|Debug|DetectSample|Runtime is over 90 seconds
2023-03-29 15:38:02.3|Debug|Parser|Parsing string 'evilangel.20.09.23.paige.owens.oil-soaked.anal.gaping.mp4'
2023-03-29 15:38:02.3|Trace|Parser|^(?<title>.+?)?[-_. ]+(?<airyear>\d{2}|\d{4})[-_. ]+(?<airmonth>[0-1][0-9])[-_. ]+(?<airday>[0-3][0-9])(?![-_. ]+[0-3][0-9])
2023-03-29 15:38:02.3|Debug|Parser|Episode Parsed. evilangel - 2020-09-23 
2023-03-29 15:38:02.3|Debug|Parser|Languages parsed: Unknown
2023-03-29 15:38:02.3|Debug|QualityParser|Trying to parse quality for evilangel.20.09.23.paige.owens.oil-soaked.anal.gaping.mp4
2023-03-29 15:38:02.3|Debug|Parser|Quality parsed: WEBDL-480p v1
2023-03-29 15:38:02.3|Debug|Parser|Release Group parsed: soaked
2023-03-29 15:38:02.3|Debug|Parser|Parsing string 'evilangel.20.09.23.paige.owens.oil-soaked.anal.gaping'
2023-03-29 15:38:02.3|Trace|Parser|^(?<title>.+?)?[-_. ]+(?<airyear>\d{2}|\d{4})[-_. ]+(?<airmonth>[0-1][0-9])[-_. ]+(?<airday>[0-3][0-9])(?![-_. ]+[0-3][0-9])
2023-03-29 15:38:02.3|Debug|Parser|Episode Parsed. evilangel - 2020-09-23 
2023-03-29 15:38:02.3|Debug|Parser|Languages parsed: Unknown
2023-03-29 15:38:02.3|Debug|QualityParser|Trying to parse quality for evilangel.20.09.23.paige.owens.oil-soaked.anal.gaping
2023-03-29 15:38:02.3|Debug|Parser|Quality parsed: Unknown v1
2023-03-29 15:38:02.3|Debug|Parser|Release Group parsed: soaked
2023-03-29 15:38:02.3|Debug|VideoFileInfoReader|Getting media info from /mnt/xxx2/_unsorted/evilangel.20.09.23.paige.owens.oil-soaked.anal.gaping.mp4
2023-03-29 15:38:02.4|Debug|Parser|Parsing string 'evilangel.20.09.23.paige.owens.oil-soaked.anal.gaping'
2023-03-29 15:38:02.4|Trace|Parser|^(?<title>.+?)?[-_. ]+(?<airyear>\d{2}|\d{4})[-_. ]+(?<airmonth>[0-1][0-9])[-_. ]+(?<airday>[0-3][0-9])(?![-_. ]+[0-3][0-9])
2023-03-29 15:38:02.4|Debug|Parser|Episode Parsed. evilangel - 2020-09-23 
2023-03-29 15:38:02.4|Debug|Parser|Languages parsed: Unknown
2023-03-29 15:38:02.4|Debug|QualityParser|Trying to parse quality for evilangel.20.09.23.paige.owens.oil-soaked.anal.gaping
2023-03-29 15:38:02.4|Debug|Parser|Quality parsed: Unknown v1
2023-03-29 15:38:02.4|Debug|Parser|Release Group parsed: soaked
2023-03-29 15:38:02.4|Trace|AggregateLanguage|Considering Languages Unknown (Filename) from FileName
2023-03-29 15:38:02.4|Debug|AggregateLanguage|Selected languages: English
2023-03-29 15:38:02.4|Trace|AggregateQuality|Considering Source Web (Fallback) Resolution 480 (Fallback) Revision v1 from FileName
2023-03-29 15:38:02.4|Trace|AugmentQualityFromMediaInfo|Resolution 1920x1080 considered 1080p
2023-03-29 15:38:02.4|Trace|AggregateQuality|Considering Source Unknown (Default) Resolution 1080 (MediaInfo) Revision  from MediaInfo
2023-03-29 15:38:02.4|Trace|AggregateQuality|Selected Source Web (Fallback) Resolution 1080 (MediaInfo) Revision v1
2023-03-29 15:38:02.4|Debug|AggregateQuality|Using quality: WEBDL-1080p v1
2023-03-29 15:38:02.4|Debug|ImportDecisionMaker|File rejected for the following reasons: [Permanent] Invalid season or episode
2023-03-29 15:38:02.4|Trace|Http|Res: 13753 [POST] /api/v3/manualimport: 200.OK (192 ms)
2023-03-29 15:38:02.4|Debug|Api|[POST] /api/v3/manualimport: 200.OK (192 ms)
2023-03-29 15:38:06.9|Trace|Http|Req: 13754 [GET] /api/v3/episode?seriesId=65&seasonNumber=2020 (from 172.*.*.88 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36)
2023-03-29 15:38:07.0|Trace|Http|Res: 13754 [GET] /api/v3/episode?seriesId=65&seasonNumber=2020: 200.OK (8 ms)
2023-03-29 15:38:07.0|Debug|Api|[GET] /api/v3/episode?seriesId=65&seasonNumber=2020: 200.OK (8 ms)
2023-03-29 15:38:21.3|Trace|Http|Req: 13755 [GET] /api/v3/health (from 172.*.*.89 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36)
2023-03-29 15:38:21.3|Trace|Http|Res: 13755 [GET] /api/v3/health: 200.OK (2 ms)
2023-03-29 15:38:21.3|Debug|Api|[GET] /api/v3/health: 200.OK (2 ms)
2023-03-29 15:38:21.3|Trace|Http|Req: 13756 [GET] /api/v3/system/status (from 172.*.*.89 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36)
2023-03-29 15:38:21.3|Trace|Http|Req: 13757 [GET] /api/v3/diskspace (from 172.*.*.89 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36)
2023-03-29 15:38:21.3|Trace|Http|Res: 13756 [GET] /api/v3/system/status: 200.OK (3 ms)
2023-03-29 15:38:21.3|Debug|Api|[GET] /api/v3/system/status: 200.OK (3 ms)
2023-03-29 15:38:21.6|Trace|Http|Res: 13757 [GET] /api/v3/diskspace: 200.OK (266 ms)
2023-03-29 15:38:21.6|Debug|Api|[GET] /api/v3/diskspace: 200.OK (266 ms)
2023-03-29 15:38:24.3|Trace|Http|Req: 13758 [GET] /api/v3/log/file (from 172.*.*.89 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36)
2023-03-29 15:38:24.3|Trace|Http|Res: 13758 [GET] /api/v3/log/file: 200.OK (4 ms)
2023-03-29 15:38:24.3|Debug|Api|[GET] /api/v3/log/file: 200.OK (4 ms)
2023-03-29 15:38:25.2|Trace|Scheduler|Pending Tasks: 1
2023-03-29 15:38:25.2|Trace|CommandQueueManager|Publishing RefreshMonitoredDownloads
2023-03-29 15:38:25.2|Trace|CommandQueueManager|Checking if command is queued or started: RefreshMonitoredDownloads
2023-03-29 15:38:25.2|Trace|CommandQueueManager|Inserting new command: RefreshMonitoredDownloads
2023-03-29 15:38:25.2|Trace|CommandExecutor|RefreshMonitoredDownloadsCommand -> DownloadMonitoringService
2023-03-29 15:38:25.2|Trace|CommandQueueManager|Marking command as started: RefreshMonitoredDownloads
2023-03-29 15:38:25.2|Trace|HttpClient|Req: [POST] https://nzbget.domain.com:443/jsonrpc: status()
2023-03-29 15:38:25.2|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2023-03-29 15:38:29.4|Trace|HttpClient|Res: [POST] https://nzbget.domain.com:443/jsonrpc: 200.OK (1094 bytes) (4172 ms)

### Anything else?

![image](https://user-images.githubusercontent.com/31871143/228662089-c92d1a16-5c5e-4dcc-b5b2-69562b1392b5.png)

**Comment by laynlownc** [comment] 2023-05-30 20:09
This looks like the same problem I am having reported on #55

**Comment by Qstick** [comment] 2023-07-04 23:22
Dupe of #55

**Closed as not planned** 2023-07-04 23:22 UTC
Labels: Area: Metadata API
