### ISSUE TITLE
Search & download content only from specific pornstars.

### ISSUE THREAD

**Issue by StarWing01** [Whisparr/Whisparr#137] opened 2023-12-20 10:51 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Is there a possibility to only monitor scenes from a specific actress ? I only want Whisparr to download episodes starring these actresses, instead of the whole series.

### Describe the solution you'd like

I have some actresses I want to follow, but if I import them as a custom list, the whole series are added, which is unneeded. One has to manually deselect everything unwanted.

### Describe alternatives you've considered

I have no idea.

**Comment by nycedwardd** [comment] 2023-12-23 13:40
You can add a porn star as an import list by TPDb ID. Go under Settings/Import List and add a list. Under Advanced List, select TPDb Performer.  
- In the first field, add a descriptive name. 
- In the Monitor field, select Specific Episode
- In the Monitor New Scenes field, select All Scenes
- In the last field, enter the ID number of the performer as listed on TPDb.  

This will grab all scenes from that performer, as well add the sites they are on. With these settings, it will add the sites without pulling additional content from those sites.

Once a site is listed, you can click on an individual scene which will list the performer. If you click the flag next to the performer's name, a pop up will show the same dialog described above as a shortcut to adding the import list. This way, you won't have to manually look up the performer ID.

**Comment by StarWing01** [comment] 2023-12-28 06:19
That's what I did, but for some reason Whisparr keeps adding additional scenes. 
Please see attached screenshots for the performers I have and a part of the scenes which Whisparr is tagging as wanted.
![lists](https://github.com/Whisparr/Whisparr/assets/6688893/a447be63-3932-4b0b-8cc8-5be123de5392)
![wanted](https://github.com/Whisparr/Whisparr/assets/6688893/a1d18882-626e-4e22-ba26-a641fe52469a)

**Comment by bboyles303** [comment] 2023-12-28 18:12
Can confirm this. Even on 2.0.0.313 when a new studio is added due to an import list release, the current year is flagged as monitored and scenes relating to none of my import lists are being added to wanted. I've moved studios monitoring to "none" for now to prevent unwanted downloads.

**Comment by StarWing01** [comment] 2023-12-29 06:51
Again this night, I don't have "Daphne Laat" in my lists:
`2023-12-29 00:10:18.4|Info|DownloadService|Report sent to Transmission. Indexer XXXClub (Prowlarr). HollandschePassie 23 12 28 Daphne Laat Hardcore DUTCH XXX 1080p MP4-WRB [XC]`
[
![hlp](https://github.com/Whisparr/Whisparr/assets/6688893/833396a9-0a49-4bff-933a-36a6c5f12fe5)
](url)

It looks like new episodes from a site are auto-added to wanted, even if you don't have the specific performer in your lists.
Note, I did not change this site to "wanted". Whisparr changed this site because one of the performers has an episode in this series.

**Comment by bboyles303** [comment] 2023-12-29 23:21
> Can confirm this. Even on 2.0.0.313 when a new studio is added due to an import list release, the current year is flagged as monitored and scenes relating to none of my import lists are being added to wanted. I've moved studios monitoring to "none" for now to prevent unwanted downloads.

On advice in the discord, I set  "Monitor New Scenes" to "None"  for all my performers/import lists. Seems that when a list adds a new studio, even with this setting, the current year for the new site/studio gets set to monitored and new releases not related to any of my import lists get downloaded. Not sure if I'm missing something or am doing this wrong.

**Comment by 2IkHLHB** [comment] 2024-01-06 15:42
I can confirm current issue as well.

I add a performer only based on great advice given at the top of this thread. But when those sites are updates, new episodes not related to the perfomer Im interested get added and downloaded automatically.

**Comment by nycedwardd** [comment] 2024-01-09 14:31
This sounds like you should refile as a bug, not a feature request.

**Comment by Qstick** [comment] 2024-01-14 02:12
This is redone and working appropriately in v3 alpha, closing

**Closed as completed** 2024-01-14 02:12 UTC
Labels: Status: Needs Triage, Type: Feature Request
