### ISSUE TITLE
Missing includes Unmonitored scenes

### ISSUE THREAD

**Issue by Gandalf-the-Blue** [Whisparr/Whisparr#136] opened 2023-12-17 15:43 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

If one goes to the Wanted -> Missing tab,  you can see scenes which are part of a Monitored series, but the scenes themselves are unmonitored.

### Expected Behavior

Only show scenes here that are Monitored themselves.

### Environment

```markdown
- OS: Linux Debian 11
- Whisparr: 2.0.0.287
- Docker Install: nightly-1976522 by hotio
- Using Reverse Proxy: No
- Browser: Firefox
- Database: Sqlite 3.41.2
```

### What branch are you running?

Main

### Trace Logs?

No trace log required.

**Comment by ICanContributeQuestionmark** [comment] 2023-12-17 16:04
This is a dupe of #127, which has an open PR #133.

**Comment by Qstick** [comment] 2023-12-17 20:16
https://github.com/Whisparr/Whisparr/commit/1d98e83f452e8370f922c0af60881eeb63c175c0

**Closed as completed by Qstick** 2023-12-17 20:16 UTC
